### ISSUE TITLE
Screenshots.

### ISSUE THREAD

**Issue by Falkgaard** [lordme1iodas/cordless#1]
## What do you want

Screenshots.

## Why

Kinda the most basic thing to add to a software repo...

## Implementation hints

Take screenshots. Commit. Push. Add to repo description,

**Comment by wynwxst** [comment]
@Falkgaard 
1 -https://github.com/Eris9/DisCli/tree/main/.github/images
2 - https://github.com/Eris9/DisCli/tree/main/tview/demos

**Comment by wynwxst** [comment]
it is already there if you bothered to look
